[package]
name = "cargo-fnstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
inquire = "0.6.0"
which = "4.4.0"
