[package]
name = "qaf-build-utils"
description = "qaf build utils"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.70"
syn = { version = "2.0.13", features = ["full"] }
